apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Matches pods with label `app: nginx`
  ports:
  - protocol: TCP
    port: 80       # Exposed port
    targetPort: 80 # Port on the container
  type: NodePort   # Exposes the service on a port accessible outside the cluster
